'use strict';
/**
 * The 14 life dimensions and their classical reading recipes. Drives
 * answer-question.js. Full prose recipes live in references/dimensions.md;
 * this file is the machine-readable form. Sources: BPHS, Phaladeepika,
 * Saravali, Jaimini Sutras, plus Raman / K.N. Rao / P.V.R. Narasimha Rao.
 */

const DIMENSIONS = {
  career: {
    name: 'Career & Profession',
    primaryHouses: [10], secondaryHouses: [6, 11], tertiaryHouses: [2, 1, 7],
    karakas: { primary: ['Sun', 'Saturn'], secondary: ['Mercury', 'Jupiter', 'Mars', 'Venus'], jaimini: ['Amatyakaraka'] },
    mainVarga: 'D10', supportingVargas: ['D1', 'D9', 'D24'], durabilityVargas: ['D27', 'D30'], karmicVarga: 'D60',
    yogasToScan: ['Panch Mahapurusha', 'Dharma-Karmadhipati Yoga', 'Raja Yoga', 'Vipreet Raja Yoga',
      'Budhaditya Yoga', 'Neecha Bhanga Raja Yoga', 'Saraswati Yoga', 'Sasa Yoga', 'Kemadruma Yoga', 'Adhi Yoga'],
    dashaLords: ['10th lord', '10th occupants', 'Sun', 'Saturn', 'Amatyakaraka'],
    transitTriggers: ['Saturn over natal 10th or 10th lord', 'Jupiter over 10th/11th/2nd', 'Rahu over 10th', 'Sade-sati'],
    astrocartography: 'if question mentions location, foreign job, relocation',
    confidence: 'D10 birth-time sensitive (~3-5 min). Flag if accuracy worse than ±15min.',
  },
  wealth: {
    name: 'Wealth & Money',
    primaryHouses: [2, 11], secondaryHouses: [5, 9], tertiaryHouses: [1, 10, 8],
    karakas: { primary: ['Jupiter'], secondary: ['Venus', 'Mercury', 'Moon'], jaimini: [] },
    mainVarga: 'D2', supportingVargas: ['D1', 'D9', 'D11'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Dhana Yoga', 'Lakshmi Yoga', 'Maha Lakshmi Yoga', 'Chandra-Mangal Yoga', 'Vasumati Yoga',
      'Gajakesari Yoga', 'Adhi Yoga', 'Sunapha Yoga', 'Anapha Yoga', 'Durudhura Yoga', 'Kemadruma Yoga',
      'Daridra Yoga', 'Vipreet Raja Yoga', 'Neecha Bhanga Raja Yoga'],
    dashaLords: ['2nd lord', '11th lord', '5th lord', '9th lord', 'Jupiter'],
    transitTriggers: ['Jupiter over 2nd/5th/9th/11th', 'Saturn over 2nd/11th', 'Rahu over 2nd/11th'],
    astrocartography: 'if question is about best place to make money or foreign income',
    confidence: 'D2 is robust; standard tolerance.',
  },
  marriage: {
    name: 'Marriage & Partnership',
    primaryHouses: [7], secondaryHouses: [2, 8], tertiaryHouses: [5, 11, 12],
    karakas: { primary: ['Venus'], secondary: ['Jupiter', 'Mars', 'Rahu'], jaimini: ['Darakaraka'] },
    mainVarga: 'D9', supportingVargas: ['D1', 'D7', 'D12'], durabilityVargas: ['D27', 'D30'], karmicVarga: 'D60',
    yogasToScan: ['Mangal Dosha', 'Gajakesari Yoga', 'Paap Kartari Yoga', 'Shubha Kartari Yoga',
      'Vipreet Raja Yoga', 'Kemadruma Yoga'],
    dashaLords: ['7th lord', 'Venus', '7th occupants', 'Darakaraka', '2nd lord', '11th lord'],
    transitTriggers: ['Jupiter over 7th/7th lord/Venus', 'Saturn over 7th', 'Rahu-Ketu on 7th axis'],
    astrocartography: 'if question mentions foreign spouse or where partner will be met',
    confidence: 'D9 moderately birth-time sensitive (~5-7 min). Flag if accuracy worse than ±15min.',
  },
  children: {
    name: 'Children & Fertility',
    primaryHouses: [5], secondaryHouses: [9], tertiaryHouses: [7, 11, 2],
    karakas: { primary: ['Jupiter'], secondary: ['Sun', 'Venus', 'Moon', 'Mars'], jaimini: ['Putrakaraka'] },
    mainVarga: 'D7', supportingVargas: ['D1', 'D9'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Pitru Dosha', 'Kemadruma Yoga'],
    dashaLords: ['Jupiter', '5th lord', '5th occupants', 'Putrakaraka'],
    transitTriggers: ['Jupiter through 5th or over natal Jupiter', 'Saturn over 5th/5th lord'],
    astrocartography: 'rarely; only if IVF abroad or relocation-for-conception',
    confidence: 'D7 birth-time sensitivity ~9-10 min. Flag if accuracy worse than ±30min.',
    extras: ['fertilitySphutas'],
  },
  health: {
    name: 'Health & Vitality',
    primaryHouses: [1, 6], secondaryHouses: [8, 12], tertiaryHouses: [2, 4, 5],
    karakas: { primary: ['Sun', 'Moon'], secondary: ['Mars', 'Saturn', 'Mercury', 'Jupiter', 'Venus'], jaimini: [] },
    mainVarga: 'D1', supportingVargas: ['D6', 'D9'], durabilityVargas: ['D27', 'D30'], karmicVarga: 'D60',
    yogasToScan: ['Kemadruma Yoga', 'Chandra-Mangal Yoga', 'Vish Yoga', 'Shapit Dosha', 'Pitru Dosha',
      'Kaal Sarp Dosha', 'Vipreet Raja Yoga'],
    dashaLords: ['6th lord', '8th lord', '12th lord', 'malefics in 6/8/12'],
    transitTriggers: ['Saturn over Lagna/Moon/Sun', 'Mars through 1/6/8', 'Eclipses on Lagna axis or Moon', 'Sade-sati'],
    astrocartography: 'generally NOT triggered; only if user asks if their location harms health',
    confidence: 'D1 needs no extreme precision for screening. NEVER predict death or terminal diagnoses. Frame as vulnerable periods supported by preventive care.',
    ethicsCritical: true,
  },
  education: {
    name: 'Education & Learning',
    primaryHouses: [4, 5], secondaryHouses: [9, 2], tertiaryHouses: [12, 8, 3],
    karakas: { primary: ['Mercury', 'Jupiter'], secondary: ['Moon', 'Sun', 'Saturn'], jaimini: [] },
    mainVarga: 'D24', supportingVargas: ['D1', 'D9'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Saraswati Yoga', 'Budhaditya Yoga', 'Gajakesari Yoga', 'Bhadra Yoga', 'Hamsa Yoga'],
    dashaLords: ['Mercury', 'Jupiter', '4th lord', '5th lord', '9th lord'],
    transitTriggers: ['Jupiter over 5th/9th/natal Mercury', 'Saturn over 4th/9th', 'Eclipses on 4/5/9 axis'],
    astrocartography: 'if question mentions best country for studies or foreign education',
    confidence: 'D24 highly birth-time sensitive (~5-6 min). Flag if accuracy worse than ±15min — findings may be unreliable.',
  },
  property: {
    name: 'Property, Home & Assets',
    primaryHouses: [4], secondaryHouses: [2, 11, 8], tertiaryHouses: [12, 3, 1],
    karakas: { primary: ['Mars', 'Moon'], secondary: ['Venus', 'Mercury', 'Saturn'], jaimini: [] },
    mainVarga: 'D4', supportingVargas: ['D1', 'D9', 'D16'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Malavya Yoga', 'Vipreet Raja Yoga'],
    dashaLords: ['4th lord', 'Mars', 'Moon', '4th occupants', '11th lord'],
    transitTriggers: ['Jupiter over 4th/4th lord', 'Saturn over 4th', 'Rahu over 4th', 'Mars over 4th'],
    astrocartography: 'strong trigger — any buying/selling/relocating question',
    confidence: 'D4 mild birth-time sensitivity (~15 min). Standard tolerance.',
  },
  relationships: {
    name: 'Relationships, Love & Social',
    primaryHouses: [5, 11], secondaryHouses: [7, 3], tertiaryHouses: [8, 12],
    karakas: { primary: ['Venus'], secondary: ['Moon', 'Mars', 'Mercury', 'Jupiter', 'Rahu'], jaimini: [] },
    mainVarga: 'D9', supportingVargas: ['D1', 'D7'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Chandra-Mangal Yoga', 'Kemadruma Yoga', 'Adhi Yoga'],
    dashaLords: ['Venus', '5th lord', 'Rahu', '11th lord', '7th lord'],
    transitTriggers: ['Venus through 5th/7th', 'Jupiter through 5th', 'Rahu through 5th/7th'],
    astrocartography: 'if question mentions finding love abroad or best city for romance',
    confidence: 'Standard tolerance.',
  },
  family: {
    name: 'Family, Parents & Siblings',
    primaryHouses: [4, 9, 3, 11], secondaryHouses: [2, 7], tertiaryHouses: [12, 8],
    karakas: { primary: ['Sun', 'Moon'], secondary: ['Mars', 'Jupiter'], jaimini: ['Pitrukaraka', 'Matrukaraka'] },
    mainVarga: 'D12', supportingVargas: ['D1', 'D3'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Pitru Dosha', 'Shapit Dosha'],
    dashaLords: ['Sun', 'Moon', '9th lord', '4th lord', '3rd lord', '11th lord', 'Mars', 'Jupiter'],
    transitTriggers: ['Saturn over natal Sun (father)', 'Saturn over natal Moon (mother)', 'Eclipses on Sun/Moon'],
    astrocartography: 'rarely; only if relocating with family',
    confidence: 'D12 birth-time sensitivity ~10 min. Never give exact timing for parental health — only vulnerable periods supported by care.',
    ethicsCritical: true,
  },
  travel: {
    name: 'Travel & Foreign Connections',
    primaryHouses: [12], secondaryHouses: [9, 7], tertiaryHouses: [3, 4, 8],
    karakas: { primary: ['Rahu'], secondary: ['Moon', 'Jupiter', 'Saturn', 'Ketu'], jaimini: [] },
    mainVarga: 'D1', supportingVargas: ['D9', 'D10', 'D12', 'D24'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Vipreet Raja Yoga'],
    dashaLords: ['Rahu', '12th lord', '9th lord', '9th occupants', '12th occupants'],
    transitTriggers: ['Jupiter through 9th/12th', 'Rahu through 9th/12th/7th', 'Saturn through 12th'],
    astrocartography: 'ALWAYS triggered — this dimension most relies on astrocartography',
    confidence: 'Standard; astrocartography accuracy depends on coordinate precision.',
  },
  spirituality: {
    name: 'Spirituality & Dharma',
    primaryHouses: [9, 12], secondaryHouses: [5, 8], tertiaryHouses: [4],
    karakas: { primary: ['Jupiter', 'Ketu'], secondary: ['Venus', 'Saturn', 'Moon'], jaimini: ['Atmakaraka'] },
    mainVarga: 'D20', supportingVargas: ['D1', 'D9'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Moksha Yoga', 'Pravrajya Yoga', 'Kemadruma Yoga', 'Hamsa Yoga'],
    dashaLords: ['Jupiter', 'Ketu', '9th lord', '12th lord', '5th lord'],
    transitTriggers: ['Jupiter over 9th/12th', 'Saturn over 12th', 'Rahu through 9th', 'Ketu through 1st/9th'],
    astrocartography: 'rarely; only for best ashram location or where to find a guru',
    confidence: 'D20 birth-time sensitivity ~6 min. Standard tolerance.',
  },
  obstacles: {
    name: 'Obstacles, Misfortune & Enemies',
    primaryHouses: [6, 8, 12], secondaryHouses: [3, 11], tertiaryHouses: [1],
    karakas: { primary: ['Saturn', 'Mars', 'Rahu', 'Ketu'], secondary: [], jaimini: [] },
    mainVarga: 'D30', supportingVargas: ['D1', 'D6'], durabilityVargas: ['D27'], karmicVarga: 'D60',
    yogasToScan: ['Vipreet Raja Yoga', 'Kaal Sarp Dosha', 'Pitru Dosha', 'Shapit Dosha', 'Guru Chandala Yoga',
      'Angarak Yoga', 'Vish Yoga', 'Daridra Yoga', 'Kemadruma Yoga', 'Paap Kartari Yoga'],
    dashaLords: ['6th lord', '8th lord', '12th lord', 'malefics in 6/8/12'],
    transitTriggers: ['Saturn over Lagna/Moon/Sun', 'Mars+Saturn or Mars+Rahu over natal afflicted points',
      'Eclipses on Lagna axis', 'Sade-sati'],
    astrocartography: 'only if user asks whether their location is causing trouble',
    confidence: 'Never frame as fate. Always pair findings with mitigation. Never predict specific accidents/deaths as certain — use "elevated risk" framing.',
    eventStyle: true,
    ethicsCritical: true,
  },
  karma: {
    name: 'Deep Karma & Past Life',
    primaryHouses: [5, 12], secondaryHouses: [9, 8], tertiaryHouses: [],
    karakas: { primary: ['Saturn', 'Ketu', 'Rahu', 'Jupiter'], secondary: [], jaimini: ['Atmakaraka'] },
    mainVarga: 'D60', supportingVargas: ['D1', 'D9'], durabilityVargas: [], karmicVarga: 'D60',
    yogasToScan: ['Shapit Dosha', 'Pitru Dosha', 'Kaal Sarp Dosha', 'Moksha Yoga'],
    dashaLords: ['Atmakaraka', 'Saturn', 'Ketu', 'Rahu'],
    transitTriggers: ['Rahu-Ketu axis transits (~every 18 months)'],
    astrocartography: 'not relevant',
    confidence: 'ABSOLUTE rule — never run if birth_time_accuracy != "exact". Even a 5-minute error makes D60 unreliable. Return the warning and refuse to elaborate.',
    requiresExactBirthTime: true,
  },
  timing: {
    name: 'Timing & Life-Periods',
    metaDimension: true,
    primaryHouses: [], secondaryHouses: [], tertiaryHouses: [],
    karakas: { primary: [], secondary: [], jaimini: [] },
    mainVarga: 'D1', supportingVargas: [], durabilityVargas: [], karmicVarga: null,
    yogasToScan: [],
    dashaLords: [],
    transitTriggers: ['Sade-sati status', 'Jupiter gochar from natal Moon', 'Saturn/Jupiter ingresses',
      'Rahu-Ketu shifts', 'Eclipse points on natal sensitive degrees'],
    astrocartography: 'not relevant',
    confidence: 'Standard. Returns a timeline view: 0-3mo, 3-12mo, 12-24mo, 24-36mo.',
  },
};

module.exports = { DIMENSIONS };
